version: '3'

services:
    mongo:
        image: mongo

    server:
        image: mlops-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
        - 8000:8000
        depends_on:
            - mongo

    client:
        image: mlops-client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
        - 8501:8501
        depends_on:
            - server


    model_training:  # Ajout du service d'entraînement
        build:
            context: ./train  # Répertoire contenant le Dockerfile de ton modèle
            dockerfile: Dockerfile
        volumes:
            - ./train/models:/app/models  # Monte le volume local pour stocker les résultats
        command: python train.py 
        depends_on:
            - mongo





        