version: '3'

services:
  mongo:
    image: mongo

  server:
    image: ghcr.io/karamoko17/mlops-server  # GHCR URL ici
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  client:
    image: ghcr.io/karamoko17/mlops-client  # GHCR URL ici
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8501:8501

  model_training: 
    build:
      context: ./train
      dockerfile: Dockerfile
    volumes:
      - ./train/models:/app/models
    command: python train.py
