name: Docker Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow depuis GitHub

jobs:
  build_and_push:
    runs-on: ubuntu-22.04

    steps:
      # Checkout le code
      - name: Checkout code
        uses: actions/checkout@v2
      # Installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose


      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker images using docker-compose
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Pousser les images vers GHCR
      - name: Push Docker images to GHCR
        run: |
          docker-compose -f docker-compose.yml push
