name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run : echo "🔎 Le nom de votre branche est ${{ github.ref }} et votre dépôt est ${{ github.repository }}."
      - nom : Consulter le code du référentiel
        utilisations : actions/checkout@v4
      - run : echo "💡 Le dépôt ${{ github.repository }} a été cloné sur le runner."
      - run : echo "🖥️ Le workflow est maintenant prêt à tester votre code sur le runner."
      - nom : liste des fichiers dans le référentiel
        courir: |
          ls ${{ github.espace de travail }}
      - run : echo "🍏 Le statut de ce travail est ${{ job.status }}."

