name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Exécute ce workflow sur chaque commit dans la branche principale

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu

    steps:
      # Vérifie le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure Docker pour se connecter au registre GitHub
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Crée l'image Docker avec le tag approprié
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.actor }}/mlops:latest .

      # Pousse l'image vers GHCR
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.actor }}/mlops:latest
